Prepare 0.2.0 (#1425)
* Prepare 0.2.0

* Upgrade to latest electron-builder@22.11.2

to fix errors such as
```
TypeError: Cannot read property 'getType' of undefined
    at GitHubPublisher.doUploadFile (/home/runner/work/asgardex-electron/asgardex-electron/node_modules/electron-publish/src/gitHubPublisher.ts:190:36)
```
^ https://github.com/thorchain/asgardex-electron/runs/2567817280?check_suite_focus=true#step:8:220

@see https://github.com.cnpmjs.org/electron-userland/electron-builder/issues/5861